### PR TITLE
refactor(code moved to enable maven ownership): of the groupid so we …

### PR DESCRIPTION
**Pull request by v3nd3774**
…can publish this plugin

### CODE REVIEW

**Comment by v3nd3774** [comment]
This will remain a draft until we are able to test pushing to `mvn` through travis ci.

**Comment by v3nd3774** [comment]
I am working with the maven central repository on this issue to gain ownership of the `groupId` for publishing.

https://issues.sonatype.org/browse/OSSRH-73865

Created this temporary repo as per instructions to prove ownership:

https://github.com/v3nd3774/OSSRH-73865

**Comment by v3nd3774** [comment]
Will be working on these issues the bot identified later today after work:

```
central-ossrhBot Central-OSSRH added a comment - 1 minute ago
io.github.v3nd3774 has been prepared, now user(s) v3nd3774 can:
Publish snapshot and release artifacts to s01.oss.sonatype.org
Have a look at this section of our official guide for deployment instructions:
https://central.sonatype.org/publish/publish-guide/#deployment

Depending on your build configuration, your first component(s) might be released automatically after a successful deployment.
If that happens, you will see a comment on this ticket confirming that your artifact has synced to Maven Central.
If you do not see this comment within an hour or two, you can follow the steps in this section of our guide:
https://central.sonatype.org/publish/release/

######

As part of our efforts to improve the security and quality posture of the open source supply chain,
we plan to enable additional scanning of dependencies for security alerts soon. Since you're already
hosting your source code in Github, you can get these insights today by enabling Sonatype Lift.
Sonatype Lift is free forever on public repositories! Lift tells you about open source vulnerabilities
during code review, and goes beyond open source to scan your code for both code quality and security issues,
providing feedback right in your pull requests.
More information can be found at https://links.sonatype.com/products/lift/github-integration

######
```

**Comment by v3nd3774** [comment]
Next issue to tackle:

```
central-ossrhBot Central-OSSRH added a comment - 1 minute ago
io.github.v3nd3774 has been prepared, now user(s) v3nd3774 can:
Publish snapshot and release artifacts to s01.oss.sonatype.org
Have a look at this section of our official guide for deployment instructions:
https://central.sonatype.org/publish/publish-guide/#deployment

Depending on your build configuration, your first component(s) might be released automatically after a successful deployment.
If that happens, you will see a comment on this ticket confirming that your artifact has synced to Maven Central.
If you do not see this comment within an hour or two, you can follow the steps in this section of our guide:
https://central.sonatype.org/publish/release/

######

As part of our efforts to improve the security and quality posture of the open source supply chain,
we plan to enable additional scanning of dependencies for security alerts soon. Since you're already
hosting your source code in Github, you can get these insights today by enabling Sonatype Lift.
Sonatype Lift is free forever on public repositories! Lift tells you about open source vulnerabilities
during code review, and goes beyond open source to scan your code for both code quality and security issues,
providing feedback right in your pull requests.
More information can be found at https://links.sonatype.com/products/lift/github-integration

######
```

**Review by Dinesh9448 — APPROVED** [review]
looks good

**Pull request merged**
